### ISSUE TITLE
Add common RabbitMQ infrastructure

### ISSUE THREAD

**Issue by bunyodkamalov** [WoW-2-0-Projects/Feedback.Analyzer#3]
### Description
Add async communication components like event bus broker and notification subscriber

### Requirements

- project must be runnable
- dependencies must be registered to the middleware

### Deliverables

- `RabbitMqEventBusBroker` - event publisher [example](https://github.com/WoW-2-0-Projects/Training.AirBnb.Clone/blob/dev/src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/EventBus/Brokers/RabbitMqEventBusBroker.cs)
- `RabbitMqConnectionProvider` - connection provider of rabbit mq [example](https://github.com/WoW-2-0-Projects/Training.AirBnb.Clone/blob/dev/src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/EventBus/Brokers/RabbitMqConnectionProvider.cs)
- `RabbitMqConnectionSettings` - external configuration to connect rabbitmq [example](https://github.com/WoW-2-0-Projects/Training.AirBnb.Clone/blob/dev/src/Training.AirBnb.Clone.Backend/AirBnB.Infrastructure/Common/Settings/RabbitMqConnectionSettings.cs)

**Comment by sulton-max** [comment]
This issue will be fixed by issue #99
